/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutHdpRouteImport } from './routes/about-hdp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HyperloopRouteImport } from './routes/hyperloop'
import { Route as OpenPositionsRouteImport } from './routes/open-positions'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResultsAndDownloadsRouteImport } from './routes/results-and-downloads'
import { Route as TeamAndBoardRouteImport } from './routes/team-and-board'
import { Route as TestingInfrastructureRouteImport } from './routes/testing-infrastructure'
import { Route as ThechallengeHdpRouteImport } from './routes/thechallenge-hdp'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHdpRoute = AboutHdpRouteImport.update({
  id: '/about-hdp',
  path: '/about-hdp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HyperloopRoute = HyperloopRouteImport.update({
  id: '/hyperloop',
  path: '/hyperloop',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenPositionsRoute = OpenPositionsRouteImport.update({
  id: '/open-positions',
  path: '/open-positions',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAndDownloadsRoute = ResultsAndDownloadsRouteImport.update({
  id: '/results-and-downloads',
  path: '/results-and-downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamAndBoardRoute = TeamAndBoardRouteImport.update({
  id: '/team-and-board',
  path: '/team-and-board',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingInfrastructureRoute = TestingInfrastructureRouteImport.update({
  id: '/testing-infrastructure',
  path: '/testing-infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const ThechallengeHdpRoute = ThechallengeHdpRouteImport.update({
  id: '/thechallenge-hdp',
  path: '/thechallenge-hdp',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-hdp': typeof AboutHdpRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hyperloop': typeof HyperloopRoute
  '/open-positions': typeof OpenPositionsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/results-and-downloads': typeof ResultsAndDownloadsRoute
  '/team-and-board': typeof TeamAndBoardRoute
  '/testing-infrastructure': typeof TestingInfrastructureRoute
  '/thechallenge-hdp': typeof ThechallengeHdpRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-hdp': typeof AboutHdpRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hyperloop': typeof HyperloopRoute
  '/open-positions': typeof OpenPositionsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/results-and-downloads': typeof ResultsAndDownloadsRoute
  '/team-and-board': typeof TeamAndBoardRoute
  '/testing-infrastructure': typeof TestingInfrastructureRoute
  '/thechallenge-hdp': typeof ThechallengeHdpRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-hdp': typeof AboutHdpRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hyperloop': typeof HyperloopRoute
  '/open-positions': typeof OpenPositionsRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/research': typeof ResearchRoute
  '/results-and-downloads': typeof ResultsAndDownloadsRoute
  '/team-and-board': typeof TeamAndBoardRoute
  '/testing-infrastructure': typeof TestingInfrastructureRoute
  '/thechallenge-hdp': typeof ThechallengeHdpRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-hdp'
    | '/contact'
    | '/faq'
    | '/hyperloop'
    | '/open-positions'
    | '/partners'
    | '/privacy'
    | '/research'
    | '/results-and-downloads'
    | '/team-and-board'
    | '/testing-infrastructure'
    | '/thechallenge-hdp'
    | '/news/$slug'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-hdp'
    | '/contact'
    | '/faq'
    | '/hyperloop'
    | '/open-positions'
    | '/partners'
    | '/privacy'
    | '/research'
    | '/results-and-downloads'
    | '/team-and-board'
    | '/testing-infrastructure'
    | '/thechallenge-hdp'
    | '/news/$slug'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about-hdp'
    | '/contact'
    | '/faq'
    | '/hyperloop'
    | '/open-positions'
    | '/partners'
    | '/privacy'
    | '/research'
    | '/results-and-downloads'
    | '/team-and-board'
    | '/testing-infrastructure'
    | '/thechallenge-hdp'
    | '/news/$slug'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutHdpRoute: typeof AboutHdpRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HyperloopRoute: typeof HyperloopRoute
  OpenPositionsRoute: typeof OpenPositionsRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchRoute: typeof ResearchRoute
  ResultsAndDownloadsRoute: typeof ResultsAndDownloadsRoute
  TeamAndBoardRoute: typeof TeamAndBoardRoute
  TestingInfrastructureRoute: typeof TestingInfrastructureRoute
  ThechallengeHdpRoute: typeof ThechallengeHdpRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-hdp': {
      id: '/about-hdp'
      path: '/about-hdp'
      fullPath: '/about-hdp'
      preLoaderRoute: typeof AboutHdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyperloop': {
      id: '/hyperloop'
      path: '/hyperloop'
      fullPath: '/hyperloop'
      preLoaderRoute: typeof HyperloopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-positions': {
      id: '/open-positions'
      path: '/open-positions'
      fullPath: '/open-positions'
      preLoaderRoute: typeof OpenPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results-and-downloads': {
      id: '/results-and-downloads'
      path: '/results-and-downloads'
      fullPath: '/results-and-downloads'
      preLoaderRoute: typeof ResultsAndDownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-and-board': {
      id: '/team-and-board'
      path: '/team-and-board'
      fullPath: '/team-and-board'
      preLoaderRoute: typeof TeamAndBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing-infrastructure': {
      id: '/testing-infrastructure'
      path: '/testing-infrastructure'
      fullPath: '/testing-infrastructure'
      preLoaderRoute: typeof TestingInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thechallenge-hdp': {
      id: '/thechallenge-hdp'
      path: '/thechallenge-hdp'
      fullPath: '/thechallenge-hdp'
      preLoaderRoute: typeof ThechallengeHdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutHdpRoute: AboutHdpRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HyperloopRoute: HyperloopRoute,
  OpenPositionsRoute: OpenPositionsRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchRoute: ResearchRoute,
  ResultsAndDownloadsRoute: ResultsAndDownloadsRoute,
  TeamAndBoardRoute: TeamAndBoardRoute,
  TestingInfrastructureRoute: TestingInfrastructureRoute,
  ThechallengeHdpRoute: ThechallengeHdpRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
